### ISSUE TITLE
dridex sample not recognized

### ISSUE THREAD

**Issue by jonz-secops** [appgate/labs#1]
I have an xlsm that is a confirmed dridex sample, unfortunately the tool states that:

[-] Problem loading PE file: PEFormatError('DOS Header magic not found.')

sha1sum 944cfe32a51aacd0be5455dac879769e439f2ab5

**Comment by palazolo** [comment]
Hello, thank you for the feedback! 

This tool was created to extract the IOCs from Dridex loader samples, which are Portable Executable (PE) files. The file you mention seems to be a Dridex downloader, which is usually an infected document (DOC, XLS, etc), and that's why you see the error. If you have the payload hash, please, feel free to send us and we can certainly check if it's supported by the tool.

Thank you and regards,
_
Gustavo
